version: '3'

services:
  web: # Webサーバーコンテナ
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./public:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    container_name: laravel-app # コンテナ名
    depends_on:
      - app # appコンテナと連携
  app: # アプリケーションコンテナ (PHP/Laravel)
    build: ./docker/web
    volumes:
      - .:/laravel
    depends_on:
      - mysql
      - composer
      - webpack
    environment:
      DB_DATABASE: database
      DB_HOST: db-host
      DB_USERNAME: docker
      DB_PASSWORD: docker
      APP_DEBUG: "true"
      APP_KEY: "base64:KlvfsD03qAsi8eOsmSbME8HK2BiH1iIAAGtnbPU3lkc="
    command: "php artisan migrate:fresh --seed"

  mysql: # データベースコンテナ
    image: mysql:5.7
    environment: # DB設定
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    container_name: db-host

  phpmyadmin: #PHPMyAdminコンテナ
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-host # mysql container_name参照
      - PMA_USER=docker
      - PMA_PASSWORD=docker

  composer:
    image: composer
    volumes:
      - .:/app # 開発ディレクトリを公開ディレクトリにマウント
    command: "composer install"

  webpack:
    image: node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "bash", "-c", "yarn install && npm run watch-poll"]